[build]
rustdocflags = ["--default-theme", "ayu", "--document-private-items"]

[alias]
test-mock        = "test --test mock"
test-integration = "test --test integration -- --test-threads=1"
test-contract    = "test --test contract --features test-utils"
d                = "doc --no-deps"
cov      = "llvm-cov --lib --test mock --ignore-filename-regex main.rs --summary-only"
cov-open = "llvm-cov --lib --test mock --ignore-filename-regex main.rs --open"
